kind = "DojoContract"
class_hash = "0x1d5a88e9175806b6d2d2a1e8a2c3efb9b40da5fc1695b1de337809fa1aa8c3a"
original_class_hash = "0x1d5a88e9175806b6d2d2a1e8a2c3efb9b40da5fc1695b1de337809fa1aa8c3a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
