kind = "DojoContract"
class_hash = "0x3b68cac49cafb23d4a4754df7d5737fbce3a06ba42ef76a52b5cdc038270f8a"
original_class_hash = "0x3b68cac49cafb23d4a4754df7d5737fbce3a06ba42ef76a52b5cdc038270f8a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
