kind = "DojoContract"
class_hash = "0x1e5c4a70b7efadc01968d234e4e33685485116527325f5bfc3005d2ad823741"
original_class_hash = "0x1e5c4a70b7efadc01968d234e4e33685485116527325f5bfc3005d2ad823741"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
