kind = "DojoContract"
class_hash = "0x6d01ef24f3e4e9f9be7ee34890d7d0673d79aba8d7c2854c91fb4ff351eedfd"
original_class_hash = "0x6d01ef24f3e4e9f9be7ee34890d7d0673d79aba8d7c2854c91fb4ff351eedfd"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
