kind = "DojoContract"
class_hash = "0x63d684859d4f0604c603dceb1dbaf44db5d202d8581fbae0968190035d8055"
original_class_hash = "0x63d684859d4f0604c603dceb1dbaf44db5d202d8581fbae0968190035d8055"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
