kind = "DojoContract"
class_hash = "0x34f255065c607a52e558eb6d625e7fbdbea669af3a07ecb4f7fca28329d0166"
original_class_hash = "0x34f255065c607a52e558eb6d625e7fbdbea669af3a07ecb4f7fca28329d0166"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
