kind = "DojoContract"
class_hash = "0x27b7abf0f36c9d7b3b1f3557aa3742d2e778b0c50d9cbaf16a11c6ccca0e680"
original_class_hash = "0x27b7abf0f36c9d7b3b1f3557aa3742d2e778b0c50d9cbaf16a11c6ccca0e680"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
