kind = "DojoContract"
class_hash = "0x7f85575fa80633f48112c681c876d600fd299c72db8d4b3f15c9c1bbb233d4e"
original_class_hash = "0x7f85575fa80633f48112c681c876d600fd299c72db8d4b3f15c9c1bbb233d4e"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
