kind = "DojoContract"
class_hash = "0x525aec2e036bd3dcb67248b047ca61fa876dc9d30a88dc10b106f1544153963"
original_class_hash = "0x525aec2e036bd3dcb67248b047ca61fa876dc9d30a88dc10b106f1544153963"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
