kind = "DojoContract"
class_hash = "0x10b70e8a2528e91895664fbb83fe348da9aa926a8894d16cbc5da1c28786048"
original_class_hash = "0x10b70e8a2528e91895664fbb83fe348da9aa926a8894d16cbc5da1c28786048"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_listening_listening.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::listening::listening"
