kind = "DojoContract"
class_hash = "0x60d7a2e1baf1f2703152648c6a6fcbbb986300a00a87db92b0120d1358c04cd"
original_class_hash = "0x60d7a2e1baf1f2703152648c6a6fcbbb986300a00a87db92b0120d1358c04cd"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_actions_actions.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::actions::actions"
