kind = "DojoContract"
class_hash = "0x30ebbd984e3fb49f0ec22c99a8912ec0607cbacec622c881ecf8081d553fdb1"
original_class_hash = "0x30ebbd984e3fb49f0ec22c99a8912ec0607cbacec622c881ecf8081d553fdb1"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_listener_listener.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::listener::listener"
