kind = "DojoContract"
class_hash = "0x1099130f4384611389b1c2b5ffd4d4b5a459215492f2db9e0999cfa25eb6f00"
original_class_hash = "0x1099130f4384611389b1c2b5ffd4d4b5a459215492f2db9e0999cfa25eb6f00"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
