kind = "DojoContract"
class_hash = "0x7cd4a6f53160c80b168584c7a1bca84f6b30047280e93aa03ecbdb333185e0a"
original_class_hash = "0x7cd4a6f53160c80b168584c7a1bca84f6b30047280e93aa03ecbdb333185e0a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
