kind = "DojoContract"
class_hash = "0x617a3add609d0d2624f4fff0188660cd22b0ec921dffe5117e0b0d29cffc0e0"
original_class_hash = "0x617a3add609d0d2624f4fff0188660cd22b0ec921dffe5117e0b0d29cffc0e0"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
