kind = "DojoContract"
class_hash = "0x5d1072bbc6217c21992e1c0de14371e2833f99e6f716b05393aaefc49a2130f"
original_class_hash = "0x5d1072bbc6217c21992e1c0de14371e2833f99e6f716b05393aaefc49a2130f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_listener_listener.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::listener::listener"
