kind = "DojoContract"
class_hash = "0x4aeced758ae85a360c0bebd516543c63d88fcc98fb56db1075c4a4c14989623"
original_class_hash = "0x4aeced758ae85a360c0bebd516543c63d88fcc98fb56db1075c4a4c14989623"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
