kind = "DojoContract"
class_hash = "0x4b2753fbbdf0ea7b5b9bf31a74671e3c670cac2aa3942a176e15d954607c11"
original_class_hash = "0x4b2753fbbdf0ea7b5b9bf31a74671e3c670cac2aa3942a176e15d954607c11"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
