kind = "DojoContract"
class_hash = "0x17d39ed4aa24ad055c75bebf11c0c1d3abe36ecf0ede717975d3a09cab06fdf"
original_class_hash = "0x17d39ed4aa24ad055c75bebf11c0c1d3abe36ecf0ede717975d3a09cab06fdf"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_outputter_outputter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::outputter::outputter"
