kind = "DojoContract"
class_hash = "0x68c8fb6265a37c16e9ff95bf0fc9087fbf31acbea600f18d8e80858ab5beaf6"
original_class_hash = "0x68c8fb6265a37c16e9ff95bf0fc9087fbf31acbea600f18d8e80858ab5beaf6"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_spawner_spawner.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::spawner::spawner"
