kind = "DojoContract"
class_hash = "0xe8e1cc28786a1eea06b20036831126e3afdd60fdad68bf67a6b422d474774a"
original_class_hash = "0xe8e1cc28786a1eea06b20036831126e3afdd60fdad68bf67a6b422d474774a"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
