kind = "DojoContract"
class_hash = "0x47639b29771c793de9b3caf0d5e444b8089961a345963871326784c4709a52c"
original_class_hash = "0x47639b29771c793de9b3caf0d5e444b8089961a345963871326784c4709a52c"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_meatpuppet_meatpuppet.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::meatpuppet::meatpuppet"
