kind = "DojoContract"
class_hash = "0x4f2f156240ee7e1a2079ab4aed3aa817a7165dee3072177e07fae8ac50fe831"
original_class_hash = "0x4f2f156240ee7e1a2079ab4aed3aa817a7165dee3072177e07fae8ac50fe831"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
