kind = "DojoContract"
class_hash = "0x3a873c211d61b08c2edb66dafbb868ec91ae82ba54812601b2f93344fe3b890"
original_class_hash = "0x3a873c211d61b08c2edb66dafbb868ec91ae82ba54812601b2f93344fe3b890"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
