kind = "DojoContract"
class_hash = "0x4f57973469e7bfa2d1e4d16475a061daf1a0e5ea071dbe87ec5e4844505f47f"
original_class_hash = "0x4f57973469e7bfa2d1e4d16475a061daf1a0e5ea071dbe87ec5e4844505f47f"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_outputter_outputter.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::outputter::outputter"
