kind = "DojoContract"
class_hash = "0x61c88d8ab4a565b9eab601ea35c48325c271737ed8cca079730bc895c6f4f48"
original_class_hash = "0x61c88d8ab4a565b9eab601ea35c48325c271737ed8cca079730bc895c6f4f48"
base_class_hash = "0x0"
abi = "manifests/dev/abis/base/contracts/the_oruggin_trail_systems_tokeniser_tokeniser.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "the_oruggin_trail::systems::tokeniser::tokeniser"
