[package]
cairo-version = "2.6.3"
name = "the_oruggin_trail"
version = "0.1.0"

[cairo]
sierra-replace-ids = true

[scripts]
migrate = "sozo build && sozo migrate apply && ./scripts/default_auth.sh"
spawn = "./scripts/spawn.sh"
move = "./scripts/move.sh"

[dependencies]
dojo = { git = "https://github.com/dojoengine/dojo", tag = "v0.7.0-alpha.5" }

[[target.dojo]]

[tool.dojo]
initializer_class_hash = "0xbeef"

[tool.dojo.env]
rpc_url = "http://localhost:5050/"
# Default account for katana with seed = 0
account_address = "0xb3ff441a68610b30fd5e2abbf3a1548eb6ba6f3559f2862bf2dc757e5828ca"
private_key = "0x2bbf4f9fd0bbb2e60b0316c1fe0b76cf7a4d0198bd493ced9b8df2a3a24d68a"
world_address = "0x1c4cc5c5e85c9aa35805c0f135ecf79bfe0171a37e896a9b6f29d14147cb3e9"

[tool.dojo.world]
name = "The Oruggin Trail"
description = "The official unauthorised and unwanted onchain text adventure engine. hoorah!"
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/ArchetypalTech/TheOrugginTrail-DoJo/tree/main"

[tool.dojo.world.socials]
# x = "https://x.com/ohayo_dojo"
# discord = "https://discord.gg/FB2wR6uF"
# github = "https://github.com/dojoengine/dojo-starter"
# telegram = "https://t.me/dojoengine"
