levels:
- levelName: test
  rooms:
  - roomID: 13246886194600585633
    roomName: Eli's Basement
    roomDescription: |-
      the basement is a converted root cellar, with a small stool bolted to the floor
      it is not a comforting room and reminds you of far too many movies that you probably never should have watched.
      the light is just enough that you don't have to see too much.
      it smells of damp and somehow bad faith.
    roomType: basement
    objects:
    - objID: 4405246086034713577
      type: trapdoor
      material: wood
      objDescription: a slightly charcoaled wooden trap door, leads upwards
      direction: U
      destination: elis-barn.md
      actions:
      - actionID: 16332049259031098349
        type: open
        enabled: true
        revertable: false
        dBitText: the trap door, closes with a bang
        dBit: true
        affectsAction: null
    - objID: 15610790850353037754
      type: dynamite
      material: tnt
      objDescription: |-
        a stick of slightly sweaty dynamite almost like a caricature of itself.
        It's fused, certainly unstable and capable of turning things (including you)into a fine meaty mist 
        still holding exciteable explosives couldn't hurt right?
      direction: null
      destination: null
      actions:
      - actionID: 12578911564611469734
        type: explode
        enabled: false
        revertable: false
        dBitText: |-
          the dynamite detonates and luckily the blast wave passes through you. 
          you shit your pants involuntarily. 
          you are spared the clean up by dint of now being largely composed of meaty paste.
        dBit: false
        affectsAction: null
      - actionID: 6636732390253036532
        type: light
        enabled: true
        revertable: false
        dBitText: |-
          the fuse comes into menacing life, sparkling like a demented god, 
          the air fills with the smell of gunpowder. this is not at all unpleasant
        dBit: false
        affectsAction: 12578911564611469734
    objectIds:
    - 15610790850353037754
    dirObjIds:
    - 4405246086034713577
  - roomID: 15740072870286221930
    roomName: Bensons plain
    roomDescription: |-
      the plain reaches seemingly endlessly to the sky in all directions
      and the sky itself feels greasy and cold.
      pyramidal rough shapes dot the horizin and land which
      upon closer examination are made from bufalo skulls.
      The air tastes of grease and bensons.
      happy happy happy
    roomType: plain
    objects:
    - objID: 4142895348942435842
      type: path
      material: dirt
      objDescription: a path east leads upwards toward the mountains
      direction: E
      destination: walking-eagle-pass.md
      actions:
      - actionID: 16668157595971844890
        type: open
        enabled: true
        revertable: false
        dBitText: the path winds east, it is open
        dBit: true
        affectsAction: null
    - objID: 2294365566944327029
      type: path
      material: dirt
      objDescription: a path north leads toward a large wooden barn
      direction: N
      destination: elis-barn.md
      actions:
      - actionID: 13058015828559547750
        type: open
        enabled: true
        revertable: false
        dBitText: the path heads north, it leads to a barn
        dBit: true
        affectsAction: null
    - objID: 17189994194645879202
      type: ball
      material: leather
      objDescription: |-
        a knock off UEFA football
        its a bit battered and bruised
        not exactly a sphere
        but you can kick it
      direction: null
      destination: null
      actions:
      - actionID: 15552978697807030543
        type: kick
        enabled: true
        revertable: false
        dBitText: the ball bounces feebly and rolls into some dog shit. fun.
        dBit: true
        affectsAction: null
    objectIds:
    - 17189994194645879202
    dirObjIds:
    - 4142895348942435842
    - 2294365566944327029
  - roomID: 12897738261327393418
    roomName: Eli's Forge
    roomDescription: |-
      has been shuttered, well the door has been nailed shut and the window locked
      from this side. Now that the window is smashed light creeps in from the barn and through the cracks in the walls and roof
      the hearth is cold and the place smells of petrol and soot
    roomType: forge
    objects:
    - objID: 2655229238403616021
      type: window
      material: glass
      objDescription: a dusty window, at chest height
      direction: E
      destination: elis-barn.md
      actions:
      - actionID: 17136525110814971091
        type: open
        enabled: true
        revertable: false
        dBitText: the window, closes with a creak
        dBit: true
        affectsAction: null
      - actionID: 11591880505556989562
        type: break
        enabled: false
        revertable: false
        dBitText: the window, smashes, glass flies everywhere, very very satisfying
        dBit: true
        affectsAction: null
    - objID: 3265630872681576966
      type: petrol
      material: metal
      objDescription: |-
        a army issue petrol can
        trade marked Cthonian Petroleum Corp n.23
      direction: null
      destination: null
      actions:
      - actionID: 6466932570877652873
        type: burn
        enabled: true
        revertable: false
        dBitText: the petrol bursts into flames
        dBit: true
        affectsAction: null
    - objID: 5316783824151223577
      type: matches
      material: wooden
      objDescription: |-
        a wooden match box
        trade marked Shoggoth's Joy
      direction: null
      destination: null
      actions:
      - actionID: 10056273856291699603
        type: burn
        enabled: true
        revertable: false
        dBitText: the match, burns with a blue flame
        dBit: true
        affectsAction: null
    objectIds:
    - 3265630872681576966
    - 5316783824151223577
    dirObjIds:
    - 2655229238403616021
  - roomID: 8892581999139148090
    roomName: Walking Eagle Pass
    roomDescription: |-
      it winds through the mountains, the path is treacherous
      toilet papered trees cover the steep
      valley sides below you.
      On closer inspection the TP might
      be the remains of a cricket team
      or perhaps a lost and very dead KKK picnic group.
      It's brass monkeys.
    roomType: mountains
    objects:
    - objID: 745772409139972109
      type: path
      material: dirt
      objDescription: path
      direction: W
      destination: bensons-plain.md
      actions:
      - actionID: 14833044636746871315
        type: open
        enabled: true
        revertable: false
        dBitText: the path winds west, it is open
        dBit: true
        affectsAction: null
    - objID: 7479341928096534711
      type: path
      material: dirt
      objDescription: path leads east
      direction: E
      destination: the-alley-off-main-street.md
      actions:
      - actionID: 9807140808976004456
        type: open
        enabled: false
        revertable: false
        dBitText: the path winds east, through piles of fresh rubble and charred pine cones
        dBit: false
        affectsAction: null
      - actionID: 14334806480543773131
        type: disintegrate
        enabled: false
        revertable: false
        dBitText: the boulder shatters into dust and shrapnel, pieces fly, deer run startled, cows drop dead, crows and squirrels drop out of the sky. satisfying essentially.
        dBit: false
        affectsAction: 9807140808976004456
    objectIds: []
    dirObjIds:
    - 745772409139972109
    - 7479341928096534711
  - roomID: 2103159215482208020
    roomName: ''
    roomDescription: ''
    roomType: ''
    objects: []
    objectIds: []
    dirObjIds: []
  - roomID: 11107137240536497418
    roomName: Eli's Barn
    roomDescription: |-
      the barn is old and smells of old hay and oddly dissolution
      the floor is dirt and trampled dried horse shit scattered with straw and broken bottles
      the smell is not unpleasent and reminds you faintly of petrol and old socks
    roomType: barn
    objects:
    - objID: 10414226638441273874
      type: door
      material: wood
      objDescription: an old wooden barn door, leads south
      direction: S
      destination: bensons-plain.md
      actions:
      - actionID: 4328927602301159032
        type: open
        enabled: true
        revertable: false
        dBitText: the door, closes with a creak
        dBit: true
        affectsAction: null
    - objID: 4916953867006087388
      type: window
      material: glass
      objDescription: a dusty window set at chest height in the west wall
      direction: W
      destination: elis-forge.md
      actions:
      - actionID: 14604306511083742153
        type: open
        enabled: true
        revertable: false
        dBitText: the window, now broken, falls open
        dBit: true
        affectsAction: null
      - actionID: 3629301349604561982
        type: break
        enabled: true
        revertable: false
        dBitText: the window, smashes, glass flies everywhere, very very satisfying
        dBit: true
        affectsAction: null
    - objID: 2400306486137228273
      type: trapdoor
      material: wood
      objDescription: a wooden trap door, is set in the floor leading downwards
      direction: D
      destination: elis-basement.md
      actions:
      - actionID: 7672293217203074089
        type: open
        enabled: true
        revertable: false
        dBitText: the trap door, opens with a bang releasing a small puff of something troubling
        dBit: true
        affectsAction: null
    - objID: 17975420477260050648
      type: Bale
      material: hay
      objDescription: a large dry bale of hay
      direction: null
      destination: null
      actions:
      - actionID: 4600616935932793690
        type: burn
        enabled: false
        revertable: false
        dBitText: the hay bursts into blue, yellow and orange flames with a speed and a heat so intense that you jump back loosing some eyebrows and gaining a small bit of wee
        dBit: false
        affectsAction: null
      - actionID: 6511208778142832924
        type: soak
        enabled: true
        revertable: false
        dBitText: the hay soaks up the volatile liquid with gusto, the air smells potent
        dBit: false
        affectsAction: null
    objectIds:
    - 17975420477260050648
    dirObjIds:
    - 10414226638441273874
    - 4916953867006087388
    - 2400306486137228273
