kind = "DojoModel"
class_hash = "0x66ae993d5b604e46102a702fdbfadb135fe81a2604a60626da0a117e68c6eba"
original_class_hash = "0x66ae993d5b604e46102a702fdbfadb135fe81a2604a60626da0a117e68c6eba"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_spawnroom_spawnroom.json"
name = "the_oruggin_trail::models::spawnroom::spawnroom"

[[members]]
name = "id"
type = "u32"
key = true

[[members]]
name = "rooms"
type = "Array<felt252>"
key = false
