kind = "DojoModel"
class_hash = "0x45bbc3581ee6ce68c266bee1ab619a60f439ba1cc11633166fb49ba72276699"
original_class_hash = "0x45bbc3581ee6ce68c266bee1ab619a60f439ba1cc11633166fb49ba72276699"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_objectstore_object_store.json"
name = "the_oruggin_trail::meat_space::objectstore::object_store"

[[members]]
name = "objectId"
type = "felt252"
key = true

[[members]]
name = "objType"
type = "zrk::ObjectType"
key = false

[[members]]
name = "dirType"
type = "zrk::DirectionType"
key = false

[[members]]
name = "destId"
type = "felt252"
key = false

[[members]]
name = "matType"
type = "zrk::MaterialType"
key = false

[[members]]
name = "objectActionIds"
type = "Array<felt252>"
key = false

[[members]]
name = "txtDefId"
type = "felt252"
key = false
