kind = "DojoModel"
class_hash = "0x1a9fdaa927512078da6d45422e7ff428b5a3e0fe169adbbd3bf100d1e8b918f"
original_class_hash = "0x1a9fdaa927512078da6d45422e7ff428b5a3e0fe169adbbd3bf100d1e8b918f"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_player_player.json"
name = "the_oruggin_trail::models::player::player"

[[members]]
name = "player_adr"
type = "ContractAddress"
key = true

[[members]]
name = "player_id"
type = "u32"
key = false
