kind = "DojoModel"
class_hash = "0x30b4cc492a2bf2bccda187062edc325893d4a03bdfe81335322b4f2dd812fb5"
original_class_hash = "0x30b4cc492a2bf2bccda187062edc325893d4a03bdfe81335322b4f2dd812fb5"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_meat_world_txt_def_store.json"
name = "the_oruggin_trail::meat_space::meat_world::txt_def_store"

[[members]]
name = "txtDefId"
type = "felt252"
key = true

[[members]]
name = "owner"
type = "felt252"
key = false

[[members]]
name = "txtDefType"
type = "zrk::TxtDefType"
key = false

[[members]]
name = "value"
type = "ByteArray"
key = false
