kind = "DojoModel"
class_hash = "0x43d4e0bf5c6a9f8ed3a510d40d0e3bd3fbfcbd46f8de6832de79841bd3ed3d9"
original_class_hash = "0x43d4e0bf5c6a9f8ed3a510d40d0e3bd3fbfcbd46f8de6832de79841bd3ed3d9"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_meat_world_player.json"
name = "the_oruggin_trail::meat_space::meat_world::player"

[[members]]
name = "playerId"
type = "felt252"
key = true

[[members]]
name = "roomId"
type = "felt252"
key = false

[[members]]
name = "objectIds"
type = "Array<felt252>"
key = false
