kind = "DojoModel"
class_hash = "0x37078b2efdbe769371a22ae579f9f025b942b306d8136b8a659edf208ce9f9d"
original_class_hash = "0x37078b2efdbe769371a22ae579f9f025b942b306d8136b8a659edf208ce9f9d"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_output_output.json"
name = "the_oruggin_trail::models::output::output"

[[members]]
name = "playerId"
type = "ContractAddress"
key = true

[[members]]
name = "text"
type = "ByteArray"
key = false
