kind = "DojoModel"
class_hash = "0x7596bc47e5d6bd961de93e628d2c606e4573479ed71adadbfd2030cf99b3e75"
original_class_hash = "0x7596bc47e5d6bd961de93e628d2c606e4573479ed71adadbfd2030cf99b3e75"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_player_player.json"
name = "the_oruggin_trail::models::player::player"

[[members]]
name = "player_adr"
type = "ContractAddress"
key = true

[[members]]
name = "player_id"
type = "u32"
key = false

[[members]]
name = "location"
type = "felt252"
key = false
