kind = "DojoModel"
class_hash = "0x1950cd1544dbfc9b2c141d79b6dcbb8132fa784efcf0725b477ef5c54bbf6c9"
original_class_hash = "0x1950cd1544dbfc9b2c141d79b6dcbb8132fa784efcf0725b477ef5c54bbf6c9"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_roomstore_room_store.json"
name = "the_oruggin_trail::meat_space::roomstore::room_store"

[[members]]
name = "roomId"
type = "felt252"
key = true

[[members]]
name = "roomType"
type = "zrk::RoomType"
key = false

[[members]]
name = "txtDefId"
type = "felt252"
key = false

[[members]]
name = "shortTxt"
type = "ByteArray"
key = false

[[members]]
name = "objectIds"
type = "Array<felt252>"
key = false

[[members]]
name = "dirObjIds"
type = "Array<felt252>"
key = false

[[members]]
name = "players"
type = "Array<felt252>"
key = false
