kind = "DojoModel"
class_hash = "0xca8063623caeacceb90f3a8635ceba26f8c81557dcfb930b78e6c329b1b1b7"
original_class_hash = "0xca8063623caeacceb90f3a8635ceba26f8c81557dcfb930b78e6c329b1b1b7"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_tokens_object_tokens.json"
name = "the_oruggin_trail::models::tokens::object_tokens"

[[members]]
name = "tok_str"
type = "felt252"
key = true

[[members]]
name = "tok_val"
type = "ObjectType"
key = false
