kind = "DojoModel"
class_hash = "0x5361cb8d88ab42d00b53212597e5806893c3e430b31b469a28339c2c3edf19d"
original_class_hash = "0x5361cb8d88ab42d00b53212597e5806893c3e430b31b469a28339c2c3edf19d"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_meat_world_action_store.json"
name = "the_oruggin_trail::meat_space::meat_world::action_store"

[[members]]
name = "actionId"
type = "felt252"
key = true

[[members]]
name = "actionType"
type = "zrk::ActionType"
key = false

[[members]]
name = "dBitTxt"
type = "felt252"
key = false

[[members]]
name = "enabled"
type = "bool"
key = false

[[members]]
name = "revertable"
type = "bool"
key = false

[[members]]
name = "dBit"
type = "bool"
key = false

[[members]]
name = "affectsActionId"
type = "felt252"
key = false

[[members]]
name = "affectedByActionId"
type = "felt252"
key = false
