kind = "DojoModel"
class_hash = "0x3f6355a9868d63f69a9a6a3f04954be845165a553945fc94fe5ac787f3c7b75"
original_class_hash = "0x3f6355a9868d63f69a9a6a3f04954be845165a553945fc94fe5ac787f3c7b75"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_output_output.json"
name = "the_oruggin_trail::models::output::output"

[[members]]
name = "playerId"
type = "felt252"
key = true

[[members]]
name = "text_o_vision"
type = "ByteArray"
key = false
