kind = "DojoModel"
class_hash = "0x16c1338521bae7b007750b2e18253affeb7f6465522af67fac37806c2f99e57"
original_class_hash = "0x16c1338521bae7b007750b2e18253affeb7f6465522af67fac37806c2f99e57"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_meat_world_dirs.json"
name = "the_oruggin_trail::meat_space::meat_world::dirs"

[[members]]
name = "key"
type = "felt252"
key = true

[[members]]
name = "dir"
type = "zrk::DirectionType"
key = false

[[members]]
name = "tok"
type = "ByteArray"
key = false
