kind = "DojoModel"
class_hash = "0xd993053b59d33c852c2a04dee35cdba195ff82af5492cdfa92bf3d8abc52d6"
original_class_hash = "0xd993053b59d33c852c2a04dee35cdba195ff82af5492cdfa92bf3d8abc52d6"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_txtdefstore_txt_def_store.json"
name = "the_oruggin_trail::meat_space::txtdefstore::txt_def_store"

[[members]]
name = "txtDefId"
type = "felt252"
key = true

[[members]]
name = "owner"
type = "felt252"
key = false

[[members]]
name = "txtDefType"
type = "zrk::TxtDefType"
key = false

[[members]]
name = "value"
type = "ByteArray"
key = false
