kind = "DojoModel"
class_hash = "0x2973f737c20f66d1e0d90894e0d476e96611587c3d52dbb5882485487b2feed"
original_class_hash = "0x2973f737c20f66d1e0d90894e0d476e96611587c3d52dbb5882485487b2feed"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_tokens_action_tokens.json"
name = "the_oruggin_trail::models::tokens::action_tokens"

[[members]]
name = "tok_str"
type = "felt252"
key = true

[[members]]
name = "tok_val"
type = "ActionType"
key = false
