kind = "DojoModel"
class_hash = "0x370c4638798ca5d349655dfcb4b13703437a196ae29b5e4bbb3c665e35dba1f"
original_class_hash = "0x370c4638798ca5d349655dfcb4b13703437a196ae29b5e4bbb3c665e35dba1f"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_action_action.json"
name = "the_oruggin_trail::models::action::action"

[[members]]
name = "actionId"
type = "felt252"
key = true

[[members]]
name = "actionType"
type = "zrk::ActionType"
key = false

[[members]]
name = "dBitTxt"
type = "ByteArray"
key = false

[[members]]
name = "enabled"
type = "bool"
key = false

[[members]]
name = "revertable"
type = "bool"
key = false

[[members]]
name = "dBit"
type = "bool"
key = false

[[members]]
name = "affectsActionId"
type = "felt252"
key = false

[[members]]
name = "affectedByActionId"
type = "felt252"
key = false
