kind = "DojoModel"
class_hash = "0x323d5fdb208c0d725fa9e3313c0eba83822e55528e38c9de7c590e2b3ba460d"
original_class_hash = "0x323d5fdb208c0d725fa9e3313c0eba83822e55528e38c9de7c590e2b3ba460d"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_meat_space_playerstore_player_store.json"
name = "the_oruggin_trail::meat_space::playerstore::player_store"

[[members]]
name = "playerId"
type = "felt252"
key = true

[[members]]
name = "roomId"
type = "felt252"
key = false

[[members]]
name = "objectIds"
type = "Array<felt252>"
key = false
