kind = "DojoModel"
class_hash = "0x9766b6618effd6ee6f9493613a8a9e1d9fec3359789fd62f47d421412f974"
original_class_hash = "0x9766b6618effd6ee6f9493613a8a9e1d9fec3359789fd62f47d421412f974"
abi = "manifests/dev/abis/base/models/the_oruggin_trail_models_moves_moves.json"
name = "the_oruggin_trail::models::moves::moves"

[[members]]
name = "player"
type = "ContractAddress"
key = true

[[members]]
name = "remaining"
type = "u8"
key = false

[[members]]
name = "last_direction"
type = "Direction"
key = false
