[world]
kind = "WorldContract"
class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
original_class_hash = "0xa349b743d361ce4567361475a89b84a386bb383448c6926954e5fe0b525597"
abi = "manifests/dev/deployment/abis/dojo-world.json"
address = "0x7b378a92d7c10143413760513c1cded0024a02793971c8250e7ebd6531d4a58"
transaction_hash = "0x52bab86d87fc1667b189d5e61183659df97ff3f2f6b171bfb39643363688f8f"
block_number = 3
seed = "the_oruggin_trail"
manifest_name = "dojo-world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
original_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/dojo-base.json"
tag = "dojo-base"
manifest_name = "dojo-base"

[[contracts]]
kind = "DojoContract"
address = "0x49939a695c84c8a457f866d3955e84a5a13c2524812c19a199944b6582582e"
class_hash = "0x7aecea7d11924bafd51578226bc3d5b4a6b1c5496a7d2db0ff36593d27cff99"
original_class_hash = "0x7aecea7d11924bafd51578226bc3d5b4a6b1c5496a7d2db0ff36593d27cff99"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/the_oruggin_trail-meatpuppet-37b6ac73.json"
reads = []
writes = []
init_calldata = []
tag = "the_oruggin_trail-meatpuppet"
systems = ["listen"]
manifest_name = "the_oruggin_trail-meatpuppet-37b6ac73"

[[contracts]]
kind = "DojoContract"
address = "0x255c9c8a1d4b17d757c35f26781a021924c277aa40667db762b6be3f21fbfe1"
class_hash = "0x1348220d4002bc7ebb343516ce32a46cd7f23126b71619db2332b47580196a3"
original_class_hash = "0x1348220d4002bc7ebb343516ce32a46cd7f23126b71619db2332b47580196a3"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/the_oruggin_trail-outputter-1a960edf.json"
reads = []
writes = []
init_calldata = []
tag = "the_oruggin_trail-outputter"
systems = [
    "spawn",
    "updateOutput",
]
manifest_name = "the_oruggin_trail-outputter-1a960edf"

[[contracts]]
kind = "DojoContract"
address = "0x1411192a670179a5744dc1003f47d4ad515a91dab187bc21a94444783c833d7"
class_hash = "0x4ff741837b6dfdf654f2b270c9635f5eb0e7dad0b9e5bedd4c11d46696dffe5"
original_class_hash = "0x4ff741837b6dfdf654f2b270c9635f5eb0e7dad0b9e5bedd4c11d46696dffe5"
base_class_hash = "0x2427dd10a58850ac9a5ca6ce04b7771b05330fd18f2e481831ad903b969e6b2"
abi = "manifests/dev/deployment/abis/contracts/the_oruggin_trail-spawner-25ff96bc.json"
reads = []
writes = []
init_calldata = []
tag = "the_oruggin_trail-spawner"
systems = [
    "setup",
    "spawn_player",
]
manifest_name = "the_oruggin_trail-spawner-25ff96bc"

[[models]]
kind = "DojoModel"
class_hash = "0x7a3f13f878a5f931d1567d8d9b08ee59c196c001ca20570d207445c0cf0eb3e"
original_class_hash = "0x7a3f13f878a5f931d1567d8d9b08ee59c196c001ca20570d207445c0cf0eb3e"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Action-73074e1e.json"
tag = "the_oruggin_trail-Action"
qualified_path = "the_oruggin_trail::models::action::action"
manifest_name = "the_oruggin_trail-Action-73074e1e"

[[models.members]]
name = "actionId"
type = "felt252"
key = true

[[models.members]]
name = "actionType"
type = "zrk::ActionType"
key = false

[[models.members]]
name = "dBitTxt"
type = "ByteArray"
key = false

[[models.members]]
name = "enabled"
type = "bool"
key = false

[[models.members]]
name = "revertable"
type = "bool"
key = false

[[models.members]]
name = "dBit"
type = "bool"
key = false

[[models.members]]
name = "affectsActionId"
type = "felt252"
key = false

[[models.members]]
name = "affectedByActionId"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x12194d5aa61fc79f225864afe79fbfb291478363f869f215f221f83d4fc2a99"
original_class_hash = "0x12194d5aa61fc79f225864afe79fbfb291478363f869f215f221f83d4fc2a99"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Inventory-39e2daf9.json"
tag = "the_oruggin_trail-Inventory"
qualified_path = "the_oruggin_trail::models::inventory::inventory"
manifest_name = "the_oruggin_trail-Inventory-39e2daf9"

[[models.members]]
name = "owner_id"
type = "felt252"
key = true

[[models.members]]
name = "items"
type = "Array<felt252>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x26a9df9d86e540facdbf6778b2cacfd64ccc0c8086a1848f146371d55b42da3"
original_class_hash = "0x26a9df9d86e540facdbf6778b2cacfd64ccc0c8086a1848f146371d55b42da3"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Object-4fb4d030.json"
tag = "the_oruggin_trail-Object"
qualified_path = "the_oruggin_trail::models::object::object"
manifest_name = "the_oruggin_trail-Object-4fb4d030"

[[models.members]]
name = "objectId"
type = "felt252"
key = true

[[models.members]]
name = "objType"
type = "zrk::ObjectType"
key = false

[[models.members]]
name = "dirType"
type = "zrk::DirectionType"
key = false

[[models.members]]
name = "destId"
type = "felt252"
key = false

[[models.members]]
name = "matType"
type = "zrk::MaterialType"
key = false

[[models.members]]
name = "objectActionIds"
type = "Array<felt252>"
key = false

[[models.members]]
name = "txtDefId"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x268c55acb7eb6b574d6980ab412337b786fd8e3f7375176b679314c558bec6e"
original_class_hash = "0x268c55acb7eb6b574d6980ab412337b786fd8e3f7375176b679314c558bec6e"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Output-55f44298.json"
tag = "the_oruggin_trail-Output"
qualified_path = "the_oruggin_trail::models::output::output"
manifest_name = "the_oruggin_trail-Output-55f44298"

[[models.members]]
name = "playerId"
type = "felt252"
key = true

[[models.members]]
name = "text_o_vision"
type = "ByteArray"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x64320194e888fef620377ff8db5fa02732701b8c8efc8b3f242cfd77e3541c4"
original_class_hash = "0x64320194e888fef620377ff8db5fa02732701b8c8efc8b3f242cfd77e3541c4"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Player-320049d3.json"
tag = "the_oruggin_trail-Player"
qualified_path = "the_oruggin_trail::models::player::player"
manifest_name = "the_oruggin_trail-Player-320049d3"

[[models.members]]
name = "player_id"
type = "felt252"
key = true

[[models.members]]
name = "player_adr"
type = "ContractAddress"
key = false

[[models.members]]
name = "location"
type = "felt252"
key = false

[[models.members]]
name = "inventory"
type = "felt252"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x5a3c0fb2018a19f41f5d514a8a109d02b8a010d3f40ab01a5b746892d320681"
original_class_hash = "0x5a3c0fb2018a19f41f5d514a8a109d02b8a010d3f40ab01a5b746892d320681"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Room-29e011fc.json"
tag = "the_oruggin_trail-Room"
qualified_path = "the_oruggin_trail::models::room::room"
manifest_name = "the_oruggin_trail-Room-29e011fc"

[[models.members]]
name = "roomId"
type = "felt252"
key = true

[[models.members]]
name = "roomType"
type = "zrk::RoomType"
key = false

[[models.members]]
name = "biomeType"
type = "zrk::BiomeType"
key = false

[[models.members]]
name = "txtDefId"
type = "felt252"
key = false

[[models.members]]
name = "shortTxt"
type = "ByteArray"
key = false

[[models.members]]
name = "objectIds"
type = "Array<felt252>"
key = false

[[models.members]]
name = "dirObjIds"
type = "Array<felt252>"
key = false

[[models.members]]
name = "players"
type = "Array<felt252>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x24b5037e3a377016c1d0b2314dcb09f883a9d48f368015c3864064a0dda21d0"
original_class_hash = "0x24b5037e3a377016c1d0b2314dcb09f883a9d48f368015c3864064a0dda21d0"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Spawnroom-11d8a392.json"
tag = "the_oruggin_trail-Spawnroom"
qualified_path = "the_oruggin_trail::models::spawnroom::spawnroom"
manifest_name = "the_oruggin_trail-Spawnroom-11d8a392"

[[models.members]]
name = "id"
type = "u32"
key = true

[[models.members]]
name = "rooms"
type = "Array<felt252>"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x169bb38554007ce7e4f2854bb80d4661ca928e80301310d215bd496405e3c4c"
original_class_hash = "0x169bb38554007ce7e4f2854bb80d4661ca928e80301310d215bd496405e3c4c"
abi = "manifests/dev/deployment/abis/models/the_oruggin_trail-Txtdef-5ce86525.json"
tag = "the_oruggin_trail-Txtdef"
qualified_path = "the_oruggin_trail::models::txtdef::txtdef"
manifest_name = "the_oruggin_trail-Txtdef-5ce86525"

[[models.members]]
name = "id"
type = "felt252"
key = true

[[models.members]]
name = "owner"
type = "felt252"
key = false

[[models.members]]
name = "text"
type = "ByteArray"
key = false
